name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sdk: ['3.0.0', '3.1.0', '3.2.0', '3.9.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.sdk }}
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: dart analyze
    
    - name: Run tests
      run: dart test --coverage=coverage
    
    - name: Generate coverage report
      run: genhtml coverage/ -o coverage/html
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.9.0'
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run static analysis
      run: dart analyze --fatal-infos
    
    - name: Check for outdated dependencies
      run: dart pub outdated --mode=null-safety

  performance:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.9.0'
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run performance tests
      run: dart test --tags=performance
